#!/usr/bin/env python

import argparse
import sys

from csv2gdata import serve_content, motion_chart, line_chart, bar_chart, scatter_chart
from csvkit.table import Table

CHART_TYPES = {
    'motion_chart': motion_chart,
    'line_chart': line_chart,
    'bar_chart': bar_chart,
    'scatter_chart': scatter_chart,
    'pie_chart': pie_chart,
}
 

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Convert a CSV to the google charts data spec.')
    parser.add_argument('--file', '-f', dest='file', type=argparse.FileType('r'),
                        default=sys.stdin, help='Input gdata.')
    parser.add_argument('--serve', '-s', dest='serve', action="store_true",
                        default=False, help='Serve the chart locally using wsgiref') #TODO should probably just be a separate script
    parser.add_argument('chart', nargs=1, default="line_chart",
                        help="Chart type, one of: <{types}>".format(types="|".join(CHART_TYPES.keys())))
    args = parser.parse_args()

    data = args.file.read()
    wrapped_chart = CHART_TYPES[args.chart[0]](data)

    if args.serve:
        serve_content(str(wrapped_chart))
    else:
        sys.stdout.write(wrapped_chart)
